/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AuctionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuctionMarket__factory>;
    getContractFactory(
      name: "BaseMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseMarket__factory>;
    getContractFactory(
      name: "IAuctionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuctionMarket__factory>;
    getContractFactory(
      name: "IERC2981",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2981__factory>;
    getContractFactory(
      name: "IERC2981EditionExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2981EditionExtension__factory>;
    getContractFactory(
      name: "IRoniaMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRoniaMarket__factory>;
    getContractFactory(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETH__factory>;
    getContractFactory(
      name: "RoniaMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RoniaMarket__factory>;

    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AuctionMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AuctionMarket>;
    getContractAt(
      name: "BaseMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseMarket>;
    getContractAt(
      name: "IAuctionMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuctionMarket>;
    getContractAt(
      name: "IERC2981",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2981>;
    getContractAt(
      name: "IERC2981EditionExtension",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2981EditionExtension>;
    getContractAt(
      name: "IRoniaMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRoniaMarket>;
    getContractAt(
      name: "IWETH",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETH>;
    getContractAt(
      name: "RoniaMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RoniaMarket>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
