/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IERC2981EditionExtensionInterface extends utils.Interface {
  functions: {
    "getRoyaltiesReceiver(uint256)": FunctionFragment;
    "hasRoyalties(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getRoyaltiesReceiver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRoyalties",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRoyaltiesReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRoyalties",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IERC2981EditionExtension extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC2981EditionExtensionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRoyaltiesReceiver(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hasRoyalties(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getRoyaltiesReceiver(
    _editionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  hasRoyalties(
    _editionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getRoyaltiesReceiver(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    hasRoyalties(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getRoyaltiesReceiver(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRoyalties(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRoyaltiesReceiver(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRoyalties(
      _editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
